grand_site/backend/urls.py
from django.urls import path
from . import views


app_name = 'backend'

urlpatterns = [
    path('', views.index, name='start'),
]

grand_site/grand_site/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('backend.urls')),
    path('__debug__/', include('debug_toolbar.urls')),

]

grand_site/backend/models.py
from django.db import models

# Create your models here.

grand_site/backend/views.py
from django.shortcuts import render


def index(request):
    template = 'index.html'
    context = {}
    return render(request, template, context)

grand_site/backend/templates/index.html
{% extends 'core/templates/bootstrap_base.html' %}
{% block table_head %}
{% endblock table_head %}
{% block content %}

test
{% endblock content %}

grand_site/core/templates/bootstrap_base.html
{% load static %}
<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %}{% endblock title %}
    <link href="{% static 'backend/css/headers.css' %}" rel="stylesheet" type="text/css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    {% block table_head %}
    {% endblock table_head %}
   
  </head>
  <body>
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
      <a href="{% url 'backend:start' %}" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
        <img src="{% static 'images/logo.png' %}" class="d-inline-block align-top" alt="" style="margin-left:10%;"> 
      </a>
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a href="#" class="nav-link" aria-current="page">
            <img src="{% static 'images/icon-user.png' %}" width="35" height="35" class="d-inline-block align-top" alt="" title="Авторизация" > 
          </a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">
            <img src="{% static 'images/icon-help.png' %}" width="40" height="40"  alt="" title="Помощь"> 
          </a>
        </li>
        {% comment %} <li class="nav-item"><a href="#" class="nav-link">Pricing</a></li>
        <li class="nav-item"><a href="#" class="nav-link">FAQs</a></li>
        <li class="nav-item"><a href="#" class="nav-link">About</a></li> {% endcomment %}
      </ul>
    </header>
    <main> 
      {% block content %}
      
      
  
      {% endblock %}
    </main>
          
    <footer class="border-top text-center py-3">
    </footer>
  </body>
</html>